import type { Metadata } from "next";
import "./globals.css";
import clsx from "clsx";
import { merriweather, merriweather_sans } from "./_utils/fonts";
import { ThemeModeScript } from "flowbite-react";

export const metadata: Metadata = {
  title: "Hanantyo's Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>

      <body className={clsx(merriweather_sans.className, "overscroll-none ")}>
        {children}
      </body>
    </html>
  );
}
